### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by koloks** [datawookie/clockify#10]
Hi Team I have an R studio script which was functioning but is now returning Error: Client error: (404) Not Found
Until a few days ago the package was working. More specifically I can retrieve a workspace if but the users command retrieves the error above

**Comment by datawookie** [comment]
Hi @koloks, can you please provide some more information? Without knowing which function is not working it's difficult for me to help. Regards, Andrew.

**Comment by koloks** [comment]
Hi Andrew I have a script built to connect to cloudy form r studio which worked until a few days ago. 

The script connects and I can execute the workspaces command and return values


When I run users () it returns a 303 error.  Ie I cannot run any queries on a specific user id 

Spiro 

Sent from my iPhone

On 1 Aug 2022, at 2:34 pm, Andrew Collier ***@***.***> wrote:

﻿
Hi @koloks, can you please provide some more information? Without knowing which function is not working it's difficult for me to help. Regards, Andrew.

**Comment by datawookie** [comment]
Hi Spiro,

Thanks for the details. Can you please clarify though: you originally mentioned a 404 error. What function was that from? I'll investigate the 303 on the `users()` function now though. Let me know about the 404.

Thanks, Andrew.

**Comment by datawookie** [comment]
Hi Spiro,

I have just tested the `users()` function and it seems to work fine for me (see redacted screenshot below). Can also confirm that the `user()` function works.

Are you working with the version on CRAN? If so, can you please try updating to the development version on GitHub. Just run `remotes::install_github("datawookie/clockify")`.

Best regards, Andrew.

![image](https://user-images.githubusercontent.com/6134409/182076441-d0637b80-1f3c-4a69-98a4-c6ebbaa06be2.png)

**Comment by koloks** [comment]
Hi Andrew your dealing with a bit of a noise here…how do I find the end point?

**Comment by datawookie** [comment]
Sorry, I'm mixing terminology. The _functions_ in the R package map to _endpoints_ in the Clockify API. I have edited my previous response for clarity.

**Comment by koloks** [comment]
Thanks switching to the GitHub version worked.

**Comment by datawookie** [comment]
Great. I'll update the version on CRAN once it becomes possible to make submissions (currently closed for Summer holidays!).
